version: "3"
networks: 
  vote: 
    driver: bridge

volumes: 
   db-data: 

services: 
    vote: 
      image: phigor/vote:miniprj_1
      build:
        context: ./vode
        dockerfile: Dockerfile
      ports: 
        - 80
      networks: 
        - vote
      depends_on: 
        - redis

    redis: 
      image: redis:alpine
      networks: 
        - vote
    
    worker: 
      image: phigor/worker:miniprj_1
      build:
        context: ./worker
        dockerfile: Dockerfile
      networks: 
        - vote
      depends_on: 
        - redis
        - db
 
    db: 
      image: postgres:9.4
      environment:
        - POSTGRES_HOST_AUTH_METHOD=trust
      networks: 
        - vote
      volumes:
        - "db-data:/var/lib/postgresql/data"
   
    results: 
      image: phigor/result:miniprj_1
      build:
        context: ./result
        dockerfile: Dockerfile
      ports:
        - 5001:80
      depends_on: 
        - db
      networks: 
        - vote
    
